export default {
    NOTIFICATION: 'NOTIFICATION',
    ERROR_PAGE: 'ERROR_PAGE',
    LOADING_PAGE: 'LOADING_PAGE',
    ERROR_HANDLING: {
        KNOWN_ERROR_BUTTON: 'KNOWN_ERROR_BUTTON',
        TIMEOUT_ERROR_BUTTON: 'TIMEOUT_ERROR_BUTTON',
        ASYNC_ERROR_BUTTON: 'ASYNC_ERROR_BUTTON',
    },
}
